version: '3.9'

services:
  elasticsearch:
    container_name: lwe_elasticsearch
    build: es
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es/data/:/usr/share/elasticsearch/data/
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      #- ./es/config/logging.yml:/usr/share/elasticsearch/config/logging.yml
      - ./es/logs/:/var/log/elasticsearch/
    environment:
      - "node.name=es-node"
      - "discovery.type=single-node"
      - "cluster.name=LiferayElasticsearchCluster"
      - "bootstrap.memory_lock=true"
      - "xpack.security.enabled=true"
      - "xpack.security.authc.api_key.enabled=true"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"

  kibana:
    container_name: lwe_kibana
    image: docker.elastic.co/kibana/kibana:7.9.3
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - xpack.security.enabled=false
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"

  enterprisesearch:
    container_name: lwe_enterprisesearch
    image: docker.elastic.co/enterprise-search/enterprise-search:7.9.3
    environment:
      - "elasticsearch.host=http://elasticsearch:9200"
      - "ent_search.auth.default.source=standard"
      - "elasticsearch.username=elastic"
      - "elasticsearch.password=${ELASTIC_PASSWORD}"
      - "secret_management.encryption_keys=[${ENCRYPTION_KEYS}]"
      - "allow_es_settings_modification=true"
      - "JAVA_OPTS=-Xms2g -Xmx2g"
      - "ENT_SEARCH_DEFAULT_PASSWORD=${ENT_SEARCH_DEFAULT_PASSWORD}"
    ports:
      - 3002:3002
    depends_on:
      - elasticsearch
      - kibana
    
  mysql:
    container_name: lwe_mysql
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      # Data initialize script trigger directory. place initialize file under the mysql_init directory.
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      # persistent data directory
      - ./db/mysql_data:/var/lib/mysql
      # configuration file
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: test
      MYSQL_PASSWORD: password

  liferay:
    container_name: lwe_liferay
    image: liferay/dxp:7.3.10-dxp-2
    environment:
      - LCP_PROJECT_ENVIRONMENT=local
      - LCP_PROJECT_ID=local
      - LIFERAY_JPDA_ENABLED=true
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME=com.mysql.cj.jdbc.Driver
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME=root
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD=password
      - LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL=jdbc:mysql://mysql/lrportal?connectionCollation=utf8mb4_bin&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true&characterEncoding=utf8
      - LIFERAY_DISABLE_TRIAL_LICENSE=false
      - LIFERAY_SETUP_PERIOD_WIZARD_PERIOD_ENABLED=false
      - LIFERAY_TERMS_PERIOD_OF_PERIOD_USE_PERIOD_REQUIRED="false
      - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_ENABLED=false
      - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_CUSTOM_PERIOD_QUESTION_PERIOD_ENABLED=false
    ports:
      - "8080:8080"
      - "11311:11311"
    volumes:
      - ./liferay/files:/mnt/liferay/files
      - ./liferay/deploy:/mnt/liferay/deploy
      - ./liferay/files/data/document_library:/mnt/liferay/files/data/document_library    
    depends_on:
      - elasticsearch
      - mysql